SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
MIN_DIMENSION = min(SCREEN_WIDTH, SCREEN_HEIGHT)
MARGIN = 8

MAZE_CELL_SIZE_X = MARGIN * 2
MAZE_CELL_SIZE_Y = MAZE_CELL_SIZE_X
MAZE_NUM_COLS = (SCREEN_WIDTH - MARGIN * 2) // MAZE_CELL_SIZE_X
MAZE_NUM_ROWS = (SCREEN_HEIGHT - MARGIN * 2) // MAZE_CELL_SIZE_Y

# Create offsets to center the maze when screen width is not the same as screen height
MAZE_WIDTH = MAZE_NUM_COLS * MAZE_CELL_SIZE_X + (MARGIN * 2)
MAZE_HEIGHT = MAZE_NUM_ROWS * MAZE_CELL_SIZE_Y + (MARGIN * 2)
MAZE_X_OFFSET = (SCREEN_WIDTH - MAZE_WIDTH) // 2
MAZE_Y_OFFSET = (SCREEN_HEIGHT - MAZE_HEIGHT) // 2

CELL_DRAW_TIME = 0.001 # seconds
SOLVE_DRAW_TIME = 0.025 # seconds
